### ISSUE TITLE
Consider replacing unmaintained dependencies

### ISSUE THREAD

**Issue by stanislav-tkach** [filecoin-project/merkletree#108]
The `memmap` library is unmaintained and there are at least two forks: `mapr` and `memmap2`. Perhaps one of them should be used instead?

The same issue with the `tempdir` library that has the `tempfile` replacement.

**Comment by stanislav-tkach** [comment]
The `tempdir` dependency has been replaced in the https://github.com/filecoin-project/merkletree/pull/114 pull request, so only `memmap` remains.

**Comment by storojs72** [comment]
`memmap` replacement is addressed in https://github.com/filecoin-project/merkletree/pull/107. It is on hold until we resolve what actual dependency is better to use. See discussion in PR for more details

**Comment by storojs72** [comment]
https://github.com/filecoin-project/merkletree/pull/107 has been merged. Looks like this issue is now addressed
