### ISSUE TITLE
Replace unwrap calls with expect

### ISSUE THREAD

**Issue by cryptonemo** [filecoin-project/merkletree#116]
Related to #38

**Comment by storojs72** [comment]
I think that we probably need proper error handling instead of unwraps and expects. Delivering errors to the high level (to the public API functions, I think) should help in avoiding dangerous panics inside the MT library.

**Comment by cryptonemo** [comment]
Yes, that's always the goal, but I tend to think unwrap -> expect conversions are a good first step.  I think tackling the error handling at the API level is a great goal, but let's reserve that for now.
