### ISSUE TITLE
Version 0.22.1 will not build :-(

### ISSUE THREAD

**Issue by NossicaSystems** [filecoin-project/merkletree#126]
Hi,

When I add this version and run a build command I get an error in:

github.com-1ecc6299db9ec823\positioned-io-0.3.1\src\raf.rs:78:29

The error is:

78 |         let pos = file.seek(SeekFrom::Current(0))?;
   |                             ^^^^^^^^ use of undeclared type `SeekFrom`

Is there some other configuration required?

**Comment by vmx** [comment]
For me the following commands work:

```console
$ cd /tmp
$ mkdir merkle                                                                                                                                                                                                                     $ cd merkle
$ cargo init
$ cargo add merkletree
$ cargo build
```

Could you please provide the commands you ran and I'll have a look.

**Comment by cryptonemo** [comment]
You can also take a look at our CI showing successful builds: https://app.circleci.com/pipelines/github/filecoin-project/merkletree?branch=master

**Comment by vmx** [comment]
I close this issue as not reproducible.
